name = "ppbl2024/introduce-parameters"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'ppbl2024/introduce-parameters'"

[repository]
user = "ppbl2024"
project = "introduce-parameters"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
