name = "ppbl2024/introduce-transaction-time"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'ppbl2024/introduce-transaction-time'"

[repository]
user = "ppbl2024"
project = "introduce-transaction-time"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
