name = "ppbl-2024-aiken-examples/introduce-context"
version = "0.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'ppbl-2024-aiken-examples/introduce-context'"

[repository]
user = "ppbl-2024-aiken-examples"
project = "introduce-context"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
