name = "gimbalabs/ppbl-faucet"
version = "0.1.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'gimbalabs/ppbl-faucet'"

[repository]
user = "gimbalabs"
project = "ppbl-faucet"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.10"
source = "github"