name = "ppbl2024/introduce-datum"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'ppbl2024/introduce-datum'"

[repository]
user = "ppbl2024"
project = "introduce-datum"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.10"
source = "github"

[config]
